#!/usr/bin/env bash

# not portable, oh well
#BASEDIR=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)
# maybe later
#BASEDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
#PROJDIR="${BASEDIR}"
#cd "${PROJDIR}"
TOPDIR=$(pwd)

print_title() {
  echo "SCIPIO-ERP addons and themes git (subtree) merging script"
  echo ""
}

print_usage() {
  echo "----------
usage: ./git-addons [action] [addon-names...] [options]

actions:
  help                how this help dialog
  pull                add or merge (as appropriate) the named addon into working copy
                      using git subtree
                      --all may be specified instead of addon names to update all
                      addons already added to current working copy.
  remote-reset        force reset the remote for the specified addon(s)
                      --all may be specified instead of addon names to update all
  list                list currently installed addons
                      --all may be specified to show all recognized addons instead

options:
  -v, --verbose       verbose output
  -a, --all           for use with pull command
  -n, --dry-run       dry run (git commands not run)
  -e, --no-msg-edit   sets GIT_MERGE_AUTOEDIT=no, so no git prompts for merge messages (unless problems)
  -h, --help          general help, or help about specific command

This script uses the git subtree command to integrate SCIPIO-ERP addons
into your working copy of ScipioCE/EE (it does NOT work with submodules at this time).

Configuration can be done in the accompanying git-addons-config file, or optionally
creating a git-addons-config-local file (ignored by git).

In order to use this script with purchased addons, you must set the variable
SCIPIO_ADDONS_URL_EE in the accompanying git-addons-config script
to the base ssh://.../SCIPIO-ERP/ addons location provided when you purchase an addon.
You must also have an SSH agent loaded with your private key for access
to the Ilscipio (or other) servers.

The addons' histories will appear as squashed in your working copy.
This is normal and made required by git subtree.

For more information on git subtree, type 'git subtree --help'.

NOTE: This script handles common merge cases. If you have any issues,
you may occasionally need to consult and use the git subtree command directly.

Requirements:
* Bash 4 or higher (for Linux/Mac; for Windows, use Git Bash, Cygwin or other emulation)
* Git 2.0 or higher (with git subtree command)

Examples:

./git-addons pull angular-shop
./git-addons pull angular-shop ignite-admin-theme
./git-addons pull --all
./git-addons list --all
"
}

print_usage_cmd_pull() {
  echo "pull: add or merges the SCIPIO-ERP addon with the given addon-name.

Alternatively, if --all is provided, pulls all existing addons in the working copy.

If its component directory does not exist, it is added using 'git subtree add' command.

If its component directory already exists, it is pulled using 'git subtree pull' command.

The command internally knows the correct target folder for the SCIPIO-ERP addons.
"
}

print_usage_cmd_remote_reset() {
  echo "remote-reset: Reset remote for the addon

Supports --all to reset all addon remotes.

May be needed if you have old repository locations, because the pull command
will not override existing remotes.
"
}

print_addon_line() {
  get_addon_info "$2"
  if [ "$1" == "${ADDON_REPOTYPE}" ]; then
    local INSTSTR=$(print_addon_format)
    echo "${ADDON_NAME} -> ${ADDON_DIR} ${INSTSTR}"
  fi
}

print_addon_format() {
  if is_addon_dir_present; then
    if is_addon_subtree; then
      echo "[INSTALLED, subtree]"
    elif is_addon_submodule_known; then
      echo "[INSTALLED, submodule]"
    elif is_addon_subtree_basic; then
      echo "[PRESENT - WARNING: git log has no record of this being a git subtree! May be incompatible with script! git subtree likely to fail!]"
    elif is_addon_submodule; then
      echo "[PRESENT - WARNING: Appears to be a submodule of unknown origin! Incompatible with script!]"
    elif is_addon_dir_empty; then
      echo "[PRESENT - WARNING: Empty addon directory! Incompatible with script!]"
    else
      echo "[PRESENT - WARNING: Does not appear to be subtree-compatible! Incompatible with script!]"
    fi
  fi
}

sort_args() {
  echo "$@" | xargs -n1 | sort -u | xargs
}

list_addons_core() {
  echo -e "\nCommunity addons:"
  for ADDON; do
    print_addon_line ce "${SCIPIO_ADDON_MAP[${ADDON}]}"
  done
  echo -e "\nEnterprise addons:"
  for ADDON; do
    print_addon_line ee "${SCIPIO_ADDON_MAP[${ADDON}]}"
  done
  if [ ! -z "${SCIPIO_ADDONS_URL_DEV}" ]; then
    echo -e "\nDev addons:"
    for ADDON; do
      print_addon_line dev "${SCIPIO_ADDON_MAP[${ADDON}]}"
    done
  fi
}

list_addons() {
  get_present_addons
  echo "Addons installed in your working copy:"
  if [ -z "${ADDONS}" ]; then
    echo -e "\n(no subtree-compatible addons detected in working copy)"
    return
  fi
  local ADDONS=$(sort_args "${ADDONS}")
  list_addons_core ${ADDONS}
}

list_addons_all() {
  echo "All known SCIPIO-ERP addons:"
  local ADDONS=$(sort_args "${!SCIPIO_ADDON_MAP[@]}")
  list_addons_core ${ADDONS}
}

list_addons_all_names() {
  echo "All known SCIPIO-ERP addons:"
  local ADDONS=$(sort_args "${!SCIPIO_ADDON_MAP[@]}")
  echo "${ADDONS}"
}

print_error() {
  echo -e "ERROR: ""$@"
}

print_warn() {
  echo -e "WARNING: ""$@"
}

print_msg() {
  echo -e "$@"
}

print_verbose() {
  if [ "${VERBOSE}" -eq 1 ]; then echo -e "$@"; fi
}

debug() {
  # FIXME: this will break functionality, needs to go to log or stderr or something...
  #print_verbose "$@"
  true
}

print_error_req() {
  print_error "$@"
}

print_error_usage() {
  print_error "$@"
  echo ""
  print_usage
}

print_subheader() {
  echo -e "\n==========================="
  echo -e "$@"
  echo -e "==========================="
}

callgit() {
  if [[ "${DRYRUN}" -eq 1 ]]; then
    echo "dry-run: git $@"
    true
  else
    git "$@"
  fi
}

check_min_version() {
  local BASE=$1
  local MIN=$2
  local BASEPARTS=(${BASE//./ })
  local MINPARTS=(${MIN//./ })
  if [[ ${#BASEPARTS[@]} -lt 2 ]] || [[ ${#MINPARTS[@]} -lt 2 ]]; then
    return 2
  fi
  if [[ ${BASEPARTS[0]} -lt ${MINPARTS[0]} ]] || [[ ${BASEPARTS[0]} -eq ${MINPARTS[0]} && ${BASEPARTS[1]} -lt ${MINPARTS[1]} ]]; then
    return 1
  fi
  return 0
}

process_config() {
  declare -A SCIPIO_ADDON_DIR_MAP
  for ADDON in "${!SCIPIO_ADDON_MAP[@]}"; do
    get_addon_info "${ADDON}"
    if [ ! -z "${SCIPIO_ADDON_DIR_MAP[${ADDON_DIR}]}" ]; then
      print_error "Config error (SCIPIO_ADDON_MAP): Illegal duplicate target addon dir detected: ${ADDON_DIR}"
      return 1
    fi
    if [ "${ADDON}" != "${ADDON_NAME}" ]; then
      print_error "Config error (SCIPIO_ADDON_MAP): Illegal entry detected having array key (${ADDON}) different from name property (${ADDON_NAME}) - must be same."
      return 1
    fi
    SCIPIO_ADDON_DIR_MAP["${ADDON_DIR}"]="${ADDON_INFO_STR}"
  done
}

check_requirements() {
  if [ -z "${BASH_VERSION}" ]; then
    print_error_req "Could not detect bash version"
    return 2
  fi
  if ! check_min_version "${BASH_VERSION}" "4.0"; then
    print_error_req "insufficient bash version - required: 4.0, you: ${BASH_VERSION}"
    return 2
  fi
  local GITVERSION=$(git --version)
  if [ $? -ne 0 ] || [ -z "${GITVERSION}" ]; then
    print_error_req "Could not detect git version - is git installed?"
    return 2
  fi
  local GITVERSION=$(echo -n "${GITVERSION}" | sed -r -n 's/^git\s\s*version\s\s*(.*)$/\1/p')
  if [ $? -ne 0 ] || [ -z "${GITVERSION}" ] || ! check_min_version "${GITVERSION}" "2.0"; then
    print_error_req "Insufficient git version - required: 2.0, system: ${GITVERSION}"
    return 2
  fi
  if ! check_min_version "${GITVERSION}" "2.7"; then
    print_warn "You are running git ${GITVERSION}; this script has not been tested with git version less than 2.7"
  fi
  if ! git --help --all | grep -q 'subtree'; then
    print_error_req "git subtree command does not appear installed - upgrade git?"
    return 2
  fi
  if [ ! -e ".git/config" ]; then
    print_error_req "This directory does not appear to be a git working copy - this script requires SCIPIO-ERP git repository"
    return 2
  fi
  if [ ! -d "addons" ] || [ ! -d "themes" ]; then
    print_error_req "Addons or themes subfolder is missing from directory - invalid SCIPIO-ERP working copy"
    return 2
  fi
  if [ ! -f "framework/base/config/scipiometainfo.properties" ]; then
    print_error_req "Missing file: framework/base/config/scipiometainfo.properties - invalid SCIPIO-ERP working copy"
    return 2
  fi
  if [ -z "${SCIPIO_ADDONS_URL_EE}" ]; then
    print_msg "NOTE: The variable SCIPIO_ADDONS_URL_EE is not set. You will only be able to install community addons from Github. \
If you have purchased an addon from the Scipio store, you must input the base address (ssh://.../SCIPIO-ERP/) provided to you \
into the git-addons-config file and commit it locally (subtree commands may fail without the commit).\n"
    if [ -z "${SCIPIO_ADDONS_URL_CE}" ]; then
      print_error_req "Could not read any addons URL from git-addons-config script"
      return 2
    fi
  fi
  if [ -z "${SCIPIO_BRANCH}" ]; then
    determine_scipio_branch || return
  fi
}

determine_scipio_branch() {
  local SCPVER=$(grep '^scipio.release.branch=' "framework/base/config/scipiometainfo.properties" | cut -d= -f2)
  if [ "${SCPVER}" == "dev" ]; then
    SCIPIO_BRANCH="master"
  elif [ "${SCPVER}" == "main" ]; then
    local SCPVERSPEC=$(grep '^scipio.release.version.general=' "framework/base/config/scipiometainfo.properties" | cut -d= -f2)
    if [ -z "${SCPVERSPEC}" ]; then
      print_error_req "Scipio version in framework/base/config/scipiometainfo.properties appears invalid - try updating script?"
      return 2
    fi
    SCIPIO_BRANCH="${SCPVERSPEC}"
  else
    print_error_req "Scipio version in framework/base/config/scipiometainfo.properties appears invalid - try updating script?"
    return 2
  fi
}

extract_pos_args() {
  for ARG; do
    if [[ "${ARG}" == -* ]]; then
      return
    fi
    echo -n " ${ARG}"
  done
}

parse_options() {
  # Official options
  ACTION="$1"
  VERBOSE=0
  HELP=0
  ALLADDONS=0
  DRYRUN=0
  
  # Unofficial/unsupported options
  REBASE=0
  REPOTYPE=subtree
  DOCHECKOUT=0
  
  if [ -z "${ACTION}" ]; then
    print_error_usage "missing action argument"
    return 2
  fi

  if [ "${ACTION}" == "help" ] || [ "${ACTION}" == "-h" ] || [ "${ACTION}" == "--help" ]; then
    ACTION=help
    HELP=1
  elif [ "${ACTION}" == "pull" ]; then
    TARGETADDONS=$(extract_pos_args "${@:2}")
  elif [ "${ACTION}" == "remote-reset" ]; then
    TARGETADDONS=$(extract_pos_args "${@:2}")
  elif [ "${ACTION}" == "list" ]; then
    true
  else
    print_error_usage "Unrecognized action: ${ACTION}"
    return 2
  fi

  for ARG; do
    if [ "${ARG}" == "-v" ] || [ "${ARG}" == "--verbose" ]; then
      VERBOSE=1
    elif [ "${ARG}" == "-h" ] || [ "${ARG}" == "--help" ]; then
      HELP=1
    elif [ "${ARG}" == "-a" ] || [ "${ARG}" == "--all" ]; then
      ALLADDONS=1
      if [ ! -z "${TARGETADDONS}" ]; then
        print_error_usage "--all cannot be used at same time as addon-name list."
        return 2
      fi
    elif [ "${ARG}" == "-n" ] || [ "${ARG}" == "--dry-run" ]; then
      DRYRUN=1
    elif [ "${ARG}" == "-e" ] || [ "${ARG}" == "--no-msg-edit" ]; then
      export GIT_MERGE_AUTOEDIT=no
    elif [ "${ARG}" == "--rebase" ]; then
      REBASE=1
    elif [ "${ARG}" == "--subtree" ]; then
      # already the default
      REPOTYPE=subtree
    elif [ "${ARG}" == "--submodule" ]; then
      REPOTYPE=submodule
    elif [ "${ARG}" == "--checkout" ]; then
      DOCHECKOUT=1
    elif [[ "${ARG}" == -* ]]; then
      print_error_usage "Unrecognized option: ${ARG}"
      return 2
    fi
  done
}

process_action() {
  if [ "${ACTION}" == "help" ]; then
    print_usage
  elif [ "${ACTION}" == "pull" ]; then
    if [ "${HELP}" -eq 1 ]; then
      print_usage_cmd_pull
    else
      if [ "${ALLADDONS}" -eq 1 ]; then
        pull_addons_all || return
      else
        if [ -z "${TARGETADDONS}" ]; then
          print_error_usage "missing addon-name or --all arguments"
          return 2
        fi
        check_target_addons ${TARGETADDONS} || return
        pull_addons ${TARGETADDONS} || return
      fi
    fi
  elif [ "${ACTION}" == "remote-reset" ]; then
    if [ "${HELP}" -eq 1 ]; then
      print_usage_cmd_remote_reset
    else
      if [ "${ALLADDONS}" -eq 1 ]; then
        remote_reset_addons_all
      else
        if [ -z "${TARGETADDONS}" ]; then
          print_error_usage "missing addon-name or --all arguments"
          return 2
        fi
        check_target_addons ${TARGETADDONS} || return
        remote_reset_addons ${TARGETADDONS} || return
      fi
    fi
  elif [ "${ACTION}" == "list" ]; then
    if [ "${ALLADDONS}" -eq 1 ]; then
      list_addons_all || return
    else
      list_addons || return
    fi
  fi
}

process_main() {
  print_title || return $?
  process_config || return $?
  check_requirements || return $?
  parse_options "$@" || return $?
  process_action || return $?
}

check_target_addons() {
  for ADDON; do
    local ADDONINFO="${SCIPIO_ADDON_MAP[${ADDON}]}"
    if [ -z "${ADDONINFO}" ]; then
      print_error "Unrecognized addon: ${ADDON} (use list --all to see available)\n"
      list_addons_all_names
      return 2
    fi
  done
  return 0
}

get_present_addons() {
  ADDONS=
  for ADDON in $(sort_args "${!SCIPIO_ADDON_MAP[@]}"); do
    get_addon_info "${SCIPIO_ADDON_MAP[${ADDON}]}"
    if is_addon_dir_present; then
      ADDONS="${ADDONS} ${ADDON}"
    fi
  done
  ADDONS=$(echo ${ADDONS})
  if [ -z "${ADDONS}" ]; then
    print_msg "No addons detected in working copy; please install some addons before using --all (pull [addon-name]); use 'list --all' for available"
    return 2
  fi
  #print_msg "Addons auto-detected in working copy (--all):\n${ADDONS}"
  return 0
}

get_valid_addons() {
  ADDONS=
  for ADDON in $(sort_args "${!SCIPIO_ADDON_MAP[@]}"); do
    get_addon_info "${SCIPIO_ADDON_MAP[${ADDON}]}"
    if is_addon_supported; then
      ADDONS="${ADDONS} ${ADDON}"
    fi
  done
  ADDONS=$(echo ${ADDONS})
  if [ -z "${ADDONS}" ]; then
    print_msg "No valid addons detected in working copy; please install some addons before using --all (pull [addon-name]); use 'list --all' for available"
    return 2
  fi
  #print_msg "Addons auto-detected in working copy (--all):\n${ADDONS}"
  return 0
}

is_addon_dir_present() {
  [ ! -z "${ADDON_DIR}" ] && [ -d "${ADDON_DIR}" ]
}

is_addon_dir_empty() {
  [ ! -z "${ADDON_DIR}" ] && [ -d "${ADDON_DIR}" ] && [ -z "$(ls -A ${ADDON_DIR})" ]
}

is_addon_submodule() {
  [ ! -z "${ADDON_DIR}" ] && [ -d "${ADDON_DIR}" ] && [ -e "${ADDON_DIR}/.git" ]
}

is_addon_submodule_known() {
  is_addon_submodule && [ "${ADDON_URL}" == $(print_submodule_url_for_dir "${ADDON_DIR}") ]
}

print_submodule_url_for_dir() {
  git config --file ".gitmodules" --get "submodule.$1.url"
}

is_addon_subtree() {
  is_addon_subtree_basic && is_addon_subtree_deep
}

is_addon_subtree_basic() {
  [ ! -z "${ADDON_DIR}" ] && [ -d "${ADDON_DIR}" ] && [ ! -z "$(ls -A ${ADDON_DIR})" ] && [ ! -e "${ADDON_DIR}/.git" ]
}

is_addon_subtree_deep() {
  local latest_squash=$(find_latest_squash "${ADDON_DIR}")
  [ ! -z "${latest_squash}" ]
}

# NOTE: function imported from git package 2.17 git-subtree.sh (this is unlikely to ever change much)
find_latest_squash() {
    debug "Looking for latest squash ($dir)..."
    dir="$1"
    sq=
    main=
    sub=
    # SCIPIO: removed: missing from older git versions: --no-show-signature 
    git log --grep="^git-subtree-dir: $dir/*\$" \
        --pretty=format:'START %H%n%s%n%n%b%nEND%n' HEAD |
    while read a b junk
    do
        debug "$a $b $junk"
        debug "{{$sq/$main/$sub}}"
        case "$a" in
        START)
            sq="$b"
            ;;
        git-subtree-mainline:)
            main="$b"
            ;;
        git-subtree-split:)
            sub="$(git rev-parse "$b^0")" ||
            die "could not rev-parse split hash $b from commit $sq"
            ;;
        END)
            if test -n "$sub"
            then
                if test -n "$main"
                then
                    # a rejoin commit?
                    # Pretend its sub was a squash.
                    sq="$sub"
                fi
                debug "Squash found: $sq $sub"
                echo "$sq" "$sub"
                break
            fi
            sq=
            main=
            sub=
            ;;
        esac
    done
}

is_addon_supported() {
  is_addon_subtree || is_addon_submodule_known
}

check_addon_supported() {
  if ! is_addon_supported; then
    if is_addon_subtree_basic; then
      print_warn "Addon ${ADDON_NAME} -> ${ADDON_DIR} has no record of being a subtree in its log; git subtree pull may fail (if it does, you may need to remove the directory, re-run this script, and reapply your changes after)"
    elif is_addon_subtree; then
      local FMTSTR=$(print_addon_format)
      print_warn "Skipping ${ADDON_NAME} -> ${ADDON_DIR} - submodule URL does not match any known addon URL; assuming not a Scipio addon.\nDetected as: ${FMTSTR}"
      return 2
    else
      local FMTSTR=$(print_addon_format)
      print_warn "Skipping ${ADDON_NAME} -> ${ADDON_DIR} - does not appear to be a subtree! Cannot be managed using this script unless removed first.\nDetected as: ${FMTSTR}"
      return 2
    fi
  fi
  return 0
}

pull_addons() {
  print_msg "Target addons: $@"
  for ADDON; do
    pull_addon "${SCIPIO_ADDON_MAP[${ADDON}]}" || return
  done
}

pull_addons_all() {
  get_valid_addons || return
  print_msg "Target addons (auto-detected): ${ADDONS}\nNOTE: If any addons appear to not be detected, use list --all command for more details, or specify them explicitly."
  for ADDON in ${ADDONS}; do
    pull_addon "${SCIPIO_ADDON_MAP[${ADDON}]}" || return
  done
}

pull_addon() {
  get_addon_info "$1"
  print_subheader "${ADDON_NAME}"
  if is_addon_dir_present; then
    check_addon_supported || return 0
    if is_addon_submodule; then
      local REBASE_STR=""
      if [ "${REBASE}" -eq 1 ]; then
        local REBASE_STR=" --rebase"
      fi
      cd "${ADDON_DIR}" || { echo "Could not change into dir: ${ADDON_DIR}"; return 1; }

      local CURR_BRANCH=$(git rev-parse --abbrev-ref HEAD)
      if [ "${CURR_BRANCH}" != "${ADDON_BRANCH}" ]; then
        if [ "${DOCHECKOUT}" -eq 1 ]; then
          print_warn "The submodule is not checked out on the expected branch (${ADDON_BRANCH}); is currently on: ${CURR_BRANCH} (or detached head). Now checking out ${ADDON_BRANCH}..."
          git checkout "${ADDON_BRANCH}" || { echo "Could not checkout submodule branch ${ADDON_BRANCH}. Please verify."; return 1; }
        else
          print_error "The submodule is not checked out on the expected branch (${ADDON_BRANCH}); is currently on: ${CURR_BRANCH} (or detached head).\nIf you wish to automatically checkout the right branch, pass the --checkout option."
          return 1
        fi
      fi
      print_msg "Running 'git pull${REBASE_STR}' for existing submodule addon ${ADDON_NAME} -> ${ADDON_DIR} (branch: ${ADDON_BRANCH})..."

      git pull ${REBASE_STR} || { echo "Pull failed. Please verify, resolve conflicts and re-run script."; return 1; }
      cd "${TOPDIR}" || { echo "Could not switch back to top dir: ${TOPDIR}"; return 1; }
    else
      ensure_addon_remote || return

      print_msg "Running 'git subtree pull' for existing subtree addon ${ADDON_NAME} -> ${ADDON_DIR} (branch: ${ADDON_BRANCH})..."
      callgit subtree pull --squash "--prefix=${ADDON_DIR}" "${ADDON_NAME}" "${ADDON_BRANCH}" || { echo "Pull failed. Please verify, resolve conflicts and re-run script. [If due to conflicts, try these commands: 'git mergetool'; afterward, 'git merge --continue'; or to abort, 'git reset --hard']"; return 1; }
    fi
  else
    if [ "${REPOTYPE}" == "submodule" ]; then
      print_msg "Running 'git submodule add' for new submodule addon ${ADDON_NAME} -> ${ADDON_DIR} (branch: ${ADDON_BRANCH})..."

      git submodule add -b "${ADDON_BRANCH}" "${ADDON_URL}" "${ADDON_DIR}" || { echo "Submodule add failed. Please verify."; return 1; }
      cd "${ADDON_DIR}" || { echo "Could not change into dir: ${ADDON_DIR}"; return 1; }
      git checkout "${ADDON_BRANCH}" || { echo "Could not checkout submodule branch ${ADDON_BRANCH}. Please verify."; return 1; }
      cd "${TOPDIR}" || { echo "Could not switch back to top dir: ${TOPDIR}"; return 1; }
      print_msg "\nNOTICE: You have added a new submodule to your root project (.gitmodules and other git properties modified); you will have to commit (and push) the result in your top project manually (see 'git status', or use 'git commit -m \"Added submodule\"')"
    else
      ensure_addon_remote || return

      print_msg "Running 'git subtree add' for new subtree addon ${ADDON_NAME} -> ${ADDON_DIR} (branch: ${ADDON_BRANCH})..."
      callgit subtree add --squash "--prefix=${ADDON_DIR}" "${ADDON_NAME}" "${ADDON_BRANCH}" || { echo "Subtree add failed. Please verify."; return 1; }
    fi
  fi
}

remote_reset_addons() {
  print_msg "Target addons: $@"
  for ADDON; do
    remote_reset_addon "${SCIPIO_ADDON_MAP[${ADDON}]}" || return
  done
}

remote_reset_addons_all() {
  get_valid_addons || return
  print_msg "Target addons (auto-detected): ${ADDONS}\nNOTE: If any addons appear to not be detected, use list --all command for more details, or specify them explicitly."
  for ADDON in ${ADDONS}; do
    remote_reset_addon "${SCIPIO_ADDON_MAP[${ADDON}]}" || return
  done
}

remote_reset_addon() {
  get_addon_info "$1"
  print_subheader "${ADDON_NAME}"
  check_addon_supported || return 0
  remote_reset_addon_core
}

ensure_addon_remote() {
  if is_remote_exists "${ADDON_NAME}"; then
    return 0
  fi
  remote_reset_addon_core
}

remote_reset_addon_core() {
  echo "Setting remote for addon ${ADDON_NAME}: ${ADDON_URL}"
  if [ -z "${ADDON_URL}" ]; then
    print_error "Cannot determine a repository URL for addon ${ADDON_NAME}. Did you set SCIPIO_ADDONS_URL_EE in git-addons-config?"
    return 1
  fi
  if is_remote_exists "${ADDON_NAME}"; then
    git remote remove "${ADDON_NAME}"
  fi
  git remote add "${ADDON_NAME}" "${ADDON_URL}" || { print_error "Could not add remote for addon ${ADDON_NAME}"; return 1; }
}

is_remote_exists() {
  git remote | grep -q '^'"${1}"'$'
}

get_addon_info() {
  ADDON_INFO_STR="$1"
  ADDON_INFO=( ${ADDON_INFO_STR} )
  if [ ${#ADDON_INFO[@]} -eq 1 ]; then
    # got name only
    ADDON_INFO_STR="${SCIPIO_ADDON_MAP[$1]}"
    ADDON_INFO=( ${ADDON_INFO_STR} )
  fi
  ADDON_NAME="${ADDON_INFO[0]}"
  ADDON_DIR="${ADDON_INFO[1]}"
  ADDON_REPOTYPE="${ADDON_INFO[2]}"
  ADDON_URLPART="${ADDON_INFO[3]}"
  ADDON_URL=""
  if [[ "${ADDON_URLPART}" == *//* ]]; then # full url
    ADDON_URL="${ADDON_URLPART}"
  else # suffix only; prepend base...
    local REPOURLVAR="SCIPIO_ADDONS_URL_${ADDON_REPOTYPE^^}"
    local REPOBASEURL=${!REPOURLVAR}
    if [ ! -z "${REPOBASEURL}" ]; then
      ADDON_URL="${REPOBASEURL}${ADDON_URLPART}"
    fi
  fi
  if [[ "${ADDON_URL}" != *".git" ]]; then
    ADDON_URL="${ADDON_URL}${SCIPIO_ADDONS_URL_SUFFIX}.git"
  fi
  ADDON_BRANCHPREFIX="${ADDON_INFO[4]}"
  ADDON_BRANCHPREFIX=${ADDON_BRANCHPREFIX%"/"}
  ADDON_BRANCH="${ADDON_BRANCHPREFIX}/${SCIPIO_BRANCH}"
  ADDON_BRANCH=${ADDON_BRANCH#"/"}
}

source "./git-addons-config" || { print_error_req "git-addons-config script file is missing or not sourceable"; exit 2; }
if [ ! -z "${SCIPIO_ADDONS_CONFIG_EXT}" ] && [ -f "${SCIPIO_ADDONS_CONFIG_EXT}" ]; then
  source "${SCIPIO_ADDONS_CONFIG_EXT}" || { print_error_req "external '${SCIPIO_ADDONS_CONFIG_EXT}' config script file is not sourceable"; exit 2; }
fi
if [ -f "./addons/scipio-dev/git-addons-config-dev" ]; then
  source "./addons/scipio-dev/git-addons-config-dev" || { print_error_req "addons/scipio-dev/git-addons-config-dev script file is not sourceable"; exit 2; }
fi
if [ -f "./git-addons-config-dev" ]; then
  source "./git-addons-config-dev" || { print_error_req "git-addons-config-dev script file is not sourceable"; exit 2; }
fi
if [ -f "./git-addons-config-local" ]; then
  source "./git-addons-config-local" || { print_error_req "git-addons-config-local script file is not sourceable"; exit 2; }
fi
process_main "$@" || exit $?
