/*
 * Scipio Commerce
 * Copyright (C) Ilscipio GmbH
 *
 * This file is part of Scipio Commerce. Scipio Commerce is free software: you
 * can redistribute it and modify it under the terms of the GNU Affero General
 * Public License, version 3, as published by the Free Software Foundation.
 * Scipio Commerce is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details. You should have received a copy of the license with this
 * work (file LICENSE). If not, see <https://www.gnu.org/licenses/agpl-3.0.html>.
 * A commercial license is available from Ilscipio GmbH.
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */
package com.ilscipio.scipio.webtools.widget;

import com.ilscipio.scipio.widget.def.screen.*;
import com.ilscipio.scipio.widget.def.condition.Condition;
import com.ilscipio.scipio.widget.def.condition.ConditionNode;
import com.ilscipio.scipio.widget.def.condition.NestedCondition;
import com.ilscipio.scipio.widget.def.condition.NestedCondition2;
import com.ilscipio.scipio.widget.def.condition.impl.*;

/**
 * Auto-generated annotation-based widget definitions.
 *
 * <p>Generated from XML by convertXmlToAnnotation Gradle task.</p>
 *
 * <p>SCIPIO: 4.0.0: Auto-generated.</p>
 */
public class MiscExtraScreens {

    @Screen(name = "DemoExtraActions1", location = "component://webtools/widget/MiscExtraScreens.xml")
    @Action(type = ActionType.SET, field = "demoExtraActions1Msg", value = "This new-style actions screen should have gotten included using a delegate include-screen-actions directive by the include-screens top directive. [SUCCESS]")
    public interface DemoExtraActions1 {}

    @Screen(name = "DemoExtraActions2", location = "component://webtools/widget/MiscExtraScreens.xml")
    @Action(type = ActionType.SET, field = "demoExtraActions2Msg", value = "This old-style actions screen should have gotten included using a delegate include-screen-actions directive by the include-screens top directive. [SUCCESS]")
    public interface DemoExtraActions2 {}

    @Screen(name = "DemoExtraActions3", location = "component://webtools/widget/MiscExtraScreens.xml")
    @Action(type = ActionType.SET, field = "demoExtraActions3Msg", value = "Because this has a widget it won't be included transitively by include-screen-actions after the placeholder are generated by include-screens")
    @Section(widgets = @Widgets(value = {@Widget(type = WidgetType.LABEL, text = "DemoExtraActions3 label widget. here we print demoExtraActions3Msg: ${demoExtraActions3Msg}")}))
    public interface DemoExtraActions3 {}

    @Screen(name = "DemoExtraActions4", location = "component://webtools/widget/MiscExtraScreens.xml")
    public interface DemoExtraActions4 {}

    @Screen(name = "DemoExtraWidget1", location = "component://webtools/widget/MiscExtraScreens.xml")
    @Section(widgets = @Widgets(value = {@Widget(type = WidgetType.LABEL, text = "This is an extra widget (1) included with include-screens directive. Also tests decorator-screen with no decorator-sections defined."), @Widget(type = WidgetType.INCLUDE_SCREEN, name = "DemoExtraWidget1-part1", location = "component://webtools/widget/MiscExtraScreens.xml", shareScope = true)}))
    public interface DemoExtraWidget1 {}

    @Screen(name = "DemoExtraWidget1-part1", location = "component://webtools/widget/MiscExtraScreens.xml")
    @DecoratorScreen(
        name = "DemoExtraWidgetMidDecorator",
        location = "component://webtools/widget/MiscExtraScreens.xml"
    )
    public interface DemoExtraWidget1_part1 {}

    @Screen(name = "DemoExtraWidget2", location = "component://webtools/widget/MiscExtraScreens.xml")
    @Section(widgets = @Widgets(value = {@Widget(type = WidgetType.LABEL, text = "This is an extra widget (2) included with include-screens directive. Also tests decorator-screen with only-passthrough decorator-sections."), @Widget(type = WidgetType.INCLUDE_SCREEN, name = "DemoExtraWidget2-part1", location = "component://webtools/widget/MiscExtraScreens.xml", shareScope = true)}))
    public interface DemoExtraWidget2 {}

    @Screen(name = "DemoExtraWidget2-part1", location = "component://webtools/widget/MiscExtraScreens.xml")
    @DecoratorScreen(
        name = "DemoExtraWidgetMidDecorator",
        location = "component://webtools/widget/MiscExtraScreens.xml",
        sections = {
            @DecoratorSection(name = "section-1", value = {@Widget(type = WidgetType.LABEL, text = "decorator section 1")}),
            @DecoratorSection(name = "section-2", value = {@Widget(type = WidgetType.LABEL, text = "decorator section 2")})
        }
    )
    public interface DemoExtraWidget2_part1 {}

    @Screen(name = "DemoExtraWidgetMidDecorator", location = "component://webtools/widget/MiscExtraScreens.xml")
    @DecoratorScreen(
        name = "DemoExtraWidgetLowDecorator",
        location = "component://webtools/widget/MiscExtraScreens.xml"
    )
    public interface DemoExtraWidgetMidDecorator {}

    @Screen(name = "DemoExtraWidgetLowDecorator", location = "component://webtools/widget/MiscExtraScreens.xml")
    @Section(widgets = @Widgets(value = {@Widget(type = WidgetType.DECORATOR_SECTION_INCLUDE, name = "section-1"), @Widget(type = WidgetType.DECORATOR_SECTION_INCLUDE, name = "section-2")}))
    public interface DemoExtraWidgetLowDecorator {}

    @Screen(name = "DemoInvalidErrorActionsScreen1", location = "component://webtools/widget/MiscExtraScreens.xml")
    public interface DemoInvalidErrorActionsScreen1 {}

    @Screen(name = "DemoSimpleLabelWidget", location = "component://webtools/widget/MiscExtraScreens.xml")
    @Section(widgets = @Widgets(value = {@Widget(type = WidgetType.LABEL, text = "This is a simple label widget.")}))
    public interface DemoSimpleLabelWidget {}

    @Screen(name = "DemoLabelWidgetWithVars", location = "component://webtools/widget/MiscExtraScreens.xml")
    @Action(type = ActionType.SCRIPT, location = "component://webtools/webapp/webtools/WEB-INF/actions/generated/DemoLabelWidgetWithVars_script1.groovy")
    @Section(widgets = @Widgets(value = {@Widget(type = WidgetType.LABEL, text = "Hello from included widget. mySimpleVar1: ${groovy: context.mySimpleVar1 ?: 'missing'}. mySimpleVar2: ${groovy: context.mySimpleVar2 ?: 'missing'}.")}))
    public interface DemoLabelWidgetWithVars {}

}
