# Scipio Commerce
# Copyright (C) Ilscipio GmbH
#
# This file is part of Scipio Commerce. Scipio Commerce is free software: you
# can redistribute it and modify it under the terms of the GNU Affero General
# Public License, version 3, as published by the Free Software Foundation.
# Scipio Commerce is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
# for more details. You should have received a copy of the license with this
# work (file LICENSE). If not, see <https://www.gnu.org/licenses/agpl-3.0.html>.
# A commercial license is available from Ilscipio GmbH.
#
# SPDX-License-Identifier: AGPL-3.0-only
# SCIPIO: configuration for new SCIPIO ERP setup component

# NOTE: this default is only used if it does not already exist in the system
website.defaultInitialWebSiteId=ScipioWebStore
website.visualThemeSelectorScript=component://common/webcommon/WEB-INF/actions/includes/GetWebSiteStoreVisualThemeId.groovy

# Default default locale string - needed because we can't infer a good default from sys locale settings (FIXME?)
store.defaultLocaleString=en_US
# The initial productStoreShipMethIdList size when loading the ProductStoreData.xml data file
# NOTE: The list now attempts to automatically grow itself past this, so this can be left to the default.
store.productStoreData.productStoreShipMethId.bankSize=100

facility.defaultWeightUomId=WT_lb

store.visualThemeSetId=ECOMMERCE
store.visualThemeId=AURORA_SHOP

# Debugging flag to show all RoleTypes in system in user step drop-down
# NOTE: The organization member roles are defined in party.properties.
user.roles.show.all=false
