# Scipio Commerce
# Copyright (C) Ilscipio GmbH
#
# This file is part of Scipio Commerce. Scipio Commerce is free software: you
# can redistribute it and modify it under the terms of the GNU Affero General
# Public License, version 3, as published by the Free Software Foundation.
# Scipio Commerce is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
# for more details. You should have received a copy of the license with this
# work (file LICENSE). If not, see <https://www.gnu.org/licenses/agpl-3.0.html>.
# A commercial license is available from Ilscipio GmbH.
#
# SPDX-License-Identifier: AGPL-3.0-only
# SCIPIO: RoleType group definitions
# Format:
#   rolegroup.[groupname].[fieldfilter]
# If all left empty for a group, returns all roles. No spaces.

# ORGANIZATION_MEMBER (e.g. controls the role list in Setup User step)
rolegroup.ORGANIZATION_MEMBER.include.roleTypeId=
rolegroup.ORGANIZATION_MEMBER.include.parentTypeId=null,CUSTOMER,EMPLOYEE,ORGANIZATION_ROLE,PERSON_ROLE,REQUEST_ROLE,SALES_REP,VENDOR,WORKFLOW_ROLE
rolegroup.ORGANIZATION_MEMBER.exclude.roleTypeId=CALENDAR_ROLE,CONTENT,DISTRIBUTION_CHANNEL,HOSTING_SERVER,LOGGEDIN,MAIN_ROLE,PROSPECT,REQUEST_ROLE,WORKFLOW_ROLE
