<#--
Scipio Commerce
Copyright (C) Ilscipio GmbH

This file is part of Scipio Commerce. Scipio Commerce is free software: you
can redistribute it and modify it under the terms of the GNU Affero General
Public License, version 3, as published by the Free Software Foundation.
Scipio Commerce is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
for more details. You should have received a copy of the license with this
work (file LICENSE). If not, see <https://www.gnu.org/licenses/agpl-3.0.html>.
A commercial license is available from Ilscipio GmbH.

SPDX-License-Identifier: AGPL-3.0-only
-->
<#--
SCIPIO: 4.0.0: Aurora Shop - texts of the home sections (English, German). asH(key) falls back to English, then to
the theme labels (labels.ftl asL), then to the key. CMS content overrides these texts per section.
-->
<#assign asHomeLabels = {
"en": {
  "ShowcaseEyebrow": "What this store can do",
  "ShowcaseTitle": "One store. *Every* way to sell.",
  "ShowcaseText": "Every tile is a live product of this demo store. Open one and try it.",
  "From": "from",
  "Try": "Try it",
  "KindConfigure": "Configure it",
  "KindConfigureText": "Choose every part. The price updates as you go.",
  "KindSubscribe": "Subscribe",
  "KindSubscribeText": "Recurring deliveries and digital subscriptions.",
  "KindRent": "Rent it",
  "KindRentText": "Pick a start date and the days. The price follows.",
  "KindDownload": "Download",
  "KindDownloadText": "Digital goods, delivered after payment.",
  "KindGift": "Gift cards",
  "KindGiftText": "Any amount, sent by e-mail, used at checkout.",
  "KindService": "Book a service",
  "KindServiceText": "Services sell next to goods, with or without shipping.",
  "KindBundle": "Bundles",
  "KindBundleText": "A set that ships as one, or one you build yourself.",
  "KindVariants": "Sizes and colours",
  "KindVariantsText": "One product page. Each variant has its own stock and price.",
  "KindFinance": "Financial products",
  "KindFinanceText": "Accounts and deposits, sold like any other product.",
  "KindMadeToOrder": "Made to order",
  "KindMadeToOrderText": "Choose the options; the kitchen gets the exact order.",
  "KindMarketplace": "Marketplace",
  "KindMarketplaceText": "Many sellers, one checkout, trader data as the law asks.",
  "KindDeals": "Deals",
  "KindDealsText": "Codes, tiers and free gifts come from rules, not from fixed prices.",
  "KindGlobal": "Languages and currencies",
  "KindGlobalLang": "Languages",
  "KindGlobalLangText": "Switch now. Texts and legal pages follow.",
  "KindGlobalText": "Switch now. Prices, texts and legal pages follow.",
  "SellersCount": "sellers",
  "StoryEyebrow": "Edited by the studio",
  "StoryTitle": "This *season*",
  "StoryReview": "Customer review",
  "StoryReviews": "reviews",
  "StoryReviewOne": "review",
  "StoryFilm": "Film",
  "StoryFilmTitle": "From the roll to the print",
  "StoryMaterials": "Materials",
  "StoryMaterialsText": "Metal body, glass lens, no battery for the shutter. Built to be repaired, not replaced.",
  "RoomEyebrow": "The workspace",
  "RoomTitle": "Shop the *room*",
  "RoomText": "Select a dot to see the product.",
  "RoomProducts": "products",
  "AddAll": "Add all to bag",
  "SetEyebrow": "Build your set",
  "SetTitle": "Pick five. Pay for *three*.",
  "SetText": "Choose any five pieces from the electronics range. The promotion applies in the bag.",
  "SetOf": "of",
  "SetAdd": "Add set to bag",
  "Added": "Added to your bag.",
  "AddFailed": "Could not add every item. Please try again.",
  "ViewBag": "View bag",
  "DealsEyebrow": "Running now",
  "DealsTitle": "Deals",
  "Code": "Code",
  "Copy": "Copy",
  "Copied": "Copied",
  "NoCode": "No code needed",
  "DropEyebrow": "Next drop",
  "DropLimited": "Limited to {0}",
  "Days": "days",
  "Hours": "hours",
  "Minutes": "min",
  "Seconds": "sec",
  "NotifyMe": "Notify me",
  "NotifyText": "We e-mail you once, when it drops.",
  "OutNow": "Out now",
  "JournalEyebrow": "Stories",
  "JournalTitle": "Journal",
  "JournalAll": "All stories",
  "MoreStories": "More stories",
  "MinRead": "min read",
  "ShopTheStory": "Shop the story",
  "YoursEyebrow": "Built with Scipio ERP",
  "YoursTitle": "Make it *yours*.",
  "YoursText": "Every section of this page is a block with live store data. Switch it off, move it, fill it with your products and your words.",
  "YoursLink": "Get Scipio ERP",
  "SwitchTitle": "Sections on this page",
  "SwitchShown": "{0} of {1} shown",
  "SwitchReset": "Show all",
  "SwitchNote": "Only in your browser. In the CMS the switch applies to every visitor.",
  "SlotHero": "Hero",
  "SlotTrust": "Trust strip",
  "SlotMarquee": "Category marquee",
  "SlotRail1": "New arrivals",
  "SlotShowcase": "Showcase",
  "SlotRoom": "Shop the room",
  "SlotSellers": "New sellers",
  "SlotSet": "Build your set",
  "SlotDrop": "Next drop",
  "SlotSeason": "This season",
  "SlotDeals": "Deals",
  "SlotRail2": "Product rail",
  "SlotJournal": "Journal",
  "SlotBand": "Know what you buy",
  "SlotRules": "Rules by region",
  "SlotYours": "Make it yours",
  "RulesEyebrow": "Built into this store",
  "RulesTitle": "One store. *Every* rulebook.",
  "RulesText": "Each market has its own laws for online shops. The store knows where a visitor shops and applies the right rules. Pick a region to see what runs here now.",
  "RulesVisit": "This visit",
  "RulesRegimeEU": "EU rules apply",
  "RulesRegimeUS": "US rules apply",
  "RulesGpcOn": "Your browser sends GPC: honoured",
  "RulesGpcOff": "No GPC signal from your browser",
  "RulesCount": "{0} rules",
  "RulesNote": "An overview, not legal advice. Check your legal texts with your lawyer.",
  "RulesRegionEu": "European Union",
  "RulesRegionDe": "Germany",
  "RulesRegionUs": "United States",
  "RulesRegionCa": "California",
  "RulesActConsent": "Open cookie settings",
  "RulesActRequest": "Make a request",
  "RulesActWithdraw": "Try it",
  "RulesActNotice": "Open the notice",
  "RulesActProduct": "See a product",
  "RulesActSellers": "How we check sellers",
  "RulesActImprint": "Open the imprint",
  "RulesActTerms": "Read the terms",
  "RulesActChoices": "Open your choices",
  "RulesActNac": "Read the notice",
  "RuleConsentLaw": "GDPR \x00B7 ePrivacy Art. 5(3)",
  "RuleConsentTitle": "Fair cookie consent",
  "RuleConsentText": "No analytics or marketing script runs before a yes. Reject is one click, like accept.",
  "RuleRightsLaw": "GDPR Art. 15, 17, 20",
  "RuleRightsTitle": "Data access and deletion",
  "RuleRightsText": "Shoppers see, export and delete their data. Order records stay for the tax period.",
  "RuleWithdrawLaw": "CRD Art. 11a",
  "RuleWithdrawDate": "from 19 Jun 2026",
  "RuleWithdrawTitle": "A withdrawal button",
  "RuleWithdrawText": "Customers withdraw from a purchase online and get a confirmation by e-mail.",
  "RuleNoticeLaw": "Reg. (EU) 2025/1960",
  "RuleNoticeDate": "from 27 Sep 2026",
  "RuleNoticeTitle": "The legal guarantee notice",
  "RuleNoticeText": "The official EU notice in the shopper's language, one click from every product.",
  "RuleGaranLaw": "Dir. (EU) 2024/825",
  "RuleGaranTitle": "The GARAN durability label",
  "RuleGaranText": "When a producer guarantees more than 2 years, the harmonised label shows next to the price.",
  "RulePriceLaw": "Dir. 98/6/EC Art. 6a",
  "RulePriceTitle": "Honest discounts",
  "RulePriceText": "A reduced price shows the lowest price of the last 30 days, from the store's own price history.",
  "RuleSafetyLaw": "GPSR \x00B7 Reg. (EU) 2023/988",
  "RuleSafetyTitle": "Product safety data",
  "RuleSafetyText": "Each product page names the manufacturer, the EU responsible person and the product identifiers.",
  "RuleSellersLaw": "DSA Art. 30 \x00B7 CRD Art. 6a",
  "RuleSellersTitle": "Checked marketplace sellers",
  "RuleSellersText": "Sellers give their trader data before they sell. Shoppers see who sells and if it is a business.",
  "RulePackagingLaw": "PPWR \x00B7 Reg. (EU) 2025/40",
  "RulePackagingDate": "from 12 Aug 2026",
  "RulePackagingTitle": "Packaging data",
  "RulePackagingText": "Material, weight and recycled share of each package, for the product page and the EPR reports.",
  "RuleImprintLaw": "\x00A7 5 DDG",
  "RuleImprintTitle": "The imprint",
  "RuleImprintText": "Company, register and contact data come from one store profile and fill every legal text.",
  "RuleOrderButtonLaw": "\x00A7 312j BGB",
  "RuleOrderButtonTitle": "The order button",
  "RuleOrderButtonText": "The last button says \"zahlungspflichtig bestellen\" (order with obligation to pay), as German law asks.",
  "RuleTextsLaw": "BGB \x00B7 EGBGB \x00B7 TDDDG",
  "RuleTextsTitle": "German legal texts",
  "RuleTextsText": "Terms, privacy, cookies, withdrawal and returns ship as German templates with the store's data.",
  "RuleEprLaw": "VerpackG \x00B7 ElektroG \x00B7 BattDG",
  "RuleEprTitle": "Producer registrations",
  "RuleEprText": "Registration numbers for packaging, electrical equipment and batteries, per country and scheme.",
  "RuleGpcLaw": "GPC \x00B7 state privacy laws",
  "RuleGpcTitle": "Global Privacy Control",
  "RuleGpcText": "A GPC signal from the browser counts as an opt-out of sale and sharing. No click needed.",
  "RuleOptOutLaw": "State privacy laws",
  "RuleOptOutTitle": "Opt-out consent",
  "RuleOptOutText": "US visitors get the opt-out model and can switch off each category at any time.",
  "RuleInformLaw": "INFORM Consumers Act",
  "RuleInformTitle": "Verified sellers",
  "RuleInformText": "The store keeps the verified trader data of each seller and shows who sells each product.",
  "RulePciLaw": "PCI DSS 6.4.3, 11.6.1",
  "RulePciTitle": "Payment page scripts",
  "RulePciText": "Checkout pages send a policy with the allowed scripts. The store logs every script outside it.",
  "RuleChoicesLaw": "CCPA \x00A7 1798.135",
  "RuleChoicesTitle": "Your Privacy Choices",
  "RuleChoicesText": "The official opt-out icon and link sit in the footer of every page.",
  "RuleNacLaw": "CCPA regs \x00A7 7012",
  "RuleNacTitle": "Notice at collection",
  "RuleNacText": "Checkout links the notice where the store collects personal data.",
  "RuleRequestsLaw": "CCPA \x00A7 1798.105, 1798.110",
  "RuleRequestsTitle": "Requests to know and delete",
  "RuleRequestsText": "Verified requests, with deadlines that the staff sees in the back office."
},
"de": {
  "ShowcaseEyebrow": "Was dieser Shop kann",
  "ShowcaseTitle": "Ein Shop. *Jede* Art zu verkaufen.",
  "ShowcaseText": "Jede Kachel ist ein echtes Produkt dieses Demo-Shops. \x00D6ffnen Sie eine und probieren Sie es aus.",
  "From": "ab",
  "Try": "Ausprobieren",
  "KindConfigure": "Konfigurieren",
  "KindConfigureText": "Jedes Teil w\x00E4hlen. Der Preis rechnet mit.",
  "KindSubscribe": "Abonnieren",
  "KindSubscribeText": "Wiederkehrende Lieferungen und digitale Abos.",
  "KindRent": "Mieten",
  "KindRentText": "Startdatum und Tage w\x00E4hlen. Der Preis folgt.",
  "KindDownload": "Download",
  "KindDownloadText": "Digitale Waren, geliefert nach der Zahlung.",
  "KindGift": "Gutscheine",
  "KindGiftText": "Jeder Betrag, per E-Mail, an der Kasse eingel\x00F6st.",
  "KindService": "Service buchen",
  "KindServiceText": "Dienstleistungen neben Waren, mit oder ohne Versand.",
  "KindBundle": "Bundles",
  "KindBundleText": "Ein fertiges Set oder eines, das Sie selbst zusammenstellen.",
  "KindVariants": "Gr\x00F6\x00DFen und Farben",
  "KindVariantsText": "Eine Produktseite. Jede Variante mit eigenem Bestand und Preis.",
  "KindFinance": "Finanzprodukte",
  "KindFinanceText": "Konten und Einlagen, verkauft wie jedes andere Produkt.",
  "KindMadeToOrder": "Nach Wunsch",
  "KindMadeToOrderText": "Optionen w\x00E4hlen; die K\x00FCche bekommt genau Ihre Bestellung.",
  "KindMarketplace": "Marktplatz",
  "KindMarketplaceText": "Viele H\x00E4ndler, eine Kasse, H\x00E4ndlerangaben wie gesetzlich verlangt.",
  "KindDeals": "Aktionen",
  "KindDealsText": "Codes, Staffeln und Gratisartikel kommen aus Regeln, nicht aus festen Preisen.",
  "KindGlobal": "Sprachen und W\x00E4hrungen",
  "KindGlobalLang": "Sprachen",
  "KindGlobalLangText": "Jetzt wechseln. Texte und Rechtstexte folgen.",
  "KindGlobalText": "Jetzt wechseln. Preise, Texte und Rechtstexte folgen.",
  "SellersCount": "H\x00E4ndler",
  "StoryEyebrow": "Vom Studio ausgew\x00E4hlt",
  "StoryTitle": "Diese *Saison*",
  "StoryReview": "Kundenbewertung",
  "StoryReviews": "Bewertungen",
  "StoryReviewOne": "Bewertung",
  "StoryFilm": "Film",
  "StoryFilmTitle": "Vom Film zum Abzug",
  "StoryMaterials": "Material",
  "StoryMaterialsText": "Metallgeh\x00E4use, Glaslinse, Verschluss ohne Batterie. Gebaut zum Reparieren, nicht zum Ersetzen.",
  "RoomEyebrow": "Der Arbeitsplatz",
  "RoomTitle": "Den Raum *shoppen*",
  "RoomText": "W\x00E4hlen Sie einen Punkt, um das Produkt zu sehen.",
  "RoomProducts": "Produkte",
  "AddAll": "Alle in den Warenkorb",
  "SetEyebrow": "Ihr Set",
  "SetTitle": "F\x00FCnf w\x00E4hlen. Drei *bezahlen*.",
  "SetText": "W\x00E4hlen Sie f\x00FCnf Teile aus der Elektronik. Die Aktion gilt im Warenkorb.",
  "SetOf": "von",
  "SetAdd": "Set in den Warenkorb",
  "Added": "Im Warenkorb.",
  "AddFailed": "Nicht alle Artikel wurden hinzugef\x00FCgt. Bitte erneut versuchen.",
  "ViewBag": "Zum Warenkorb",
  "DealsEyebrow": "Jetzt aktiv",
  "DealsTitle": "Aktionen",
  "Code": "Code",
  "Copy": "Kopieren",
  "Copied": "Kopiert",
  "NoCode": "Ohne Code",
  "DropEyebrow": "N\x00E4chster Drop",
  "DropLimited": "Limitiert auf {0}",
  "Days": "Tage",
  "Hours": "Std.",
  "Minutes": "Min.",
  "Seconds": "Sek.",
  "NotifyMe": "Benachrichtigen",
  "NotifyText": "Wir schreiben Ihnen einmal, wenn es so weit ist.",
  "OutNow": "Jetzt erh\x00E4ltlich",
  "JournalEyebrow": "Geschichten",
  "JournalTitle": "Journal",
  "JournalAll": "Alle Geschichten",
  "MoreStories": "Weitere Geschichten",
  "MinRead": "Min. Lesezeit",
  "ShopTheStory": "Produkte aus der Geschichte",
  "YoursEyebrow": "Gebaut mit Scipio ERP",
  "YoursTitle": "Machen Sie ihn zu *Ihrem*.",
  "YoursText": "Jeder Abschnitt dieser Seite ist ein Block mit echten Shop-Daten. Ausschalten, verschieben, mit Ihren Produkten und Worten f\x00FCllen.",
  "YoursLink": "Scipio ERP holen",
  "SwitchTitle": "Abschnitte dieser Seite",
  "SwitchShown": "{0} von {1} sichtbar",
  "SwitchReset": "Alle zeigen",
  "SwitchNote": "Nur in Ihrem Browser. Im CMS gilt der Schalter f\x00FCr alle Besucher.",
  "SlotHero": "Aufmacher",
  "SlotTrust": "Vertrauensleiste",
  "SlotMarquee": "Kategorie-Laufband",
  "SlotRail1": "Neuheiten",
  "SlotShowcase": "Schaufenster",
  "SlotRoom": "Den Raum shoppen",
  "SlotSellers": "Neue H\x00E4ndler",
  "SlotSet": "Ihr Set",
  "SlotDrop": "N\x00E4chster Drop",
  "SlotSeason": "Diese Saison",
  "SlotDeals": "Aktionen",
  "SlotRail2": "Produktreihe",
  "SlotJournal": "Journal",
  "SlotBand": "Wissen, was Sie kaufen",
  "SlotRules": "Regeln je Region",
  "SlotYours": "Ihr Shop",
  "RulesEyebrow": "In diesen Shop eingebaut",
  "RulesTitle": "Ein Shop. *Jedes* Regelwerk.",
  "RulesText": "Jeder Markt hat eigene Gesetze f\x00FCr Online-Shops. Der Shop erkennt, wo ein Besucher einkauft, und wendet die passenden Regeln an. W\x00E4hlen Sie eine Region und sehen Sie, was hier gerade l\x00E4uft.",
  "RulesVisit": "Dieser Besuch",
  "RulesRegimeEU": "EU-Regeln gelten",
  "RulesRegimeUS": "US-Regeln gelten",
  "RulesGpcOn": "Ihr Browser sendet GPC: beachtet",
  "RulesGpcOff": "Kein GPC-Signal von Ihrem Browser",
  "RulesCount": "{0} Regeln",
  "RulesNote": "Eine \x00DCbersicht, keine Rechtsberatung. Lassen Sie Ihre Rechtstexte anwaltlich pr\x00FCfen.",
  "RulesRegionEu": "Europ\x00E4ische Union",
  "RulesRegionDe": "Deutschland",
  "RulesRegionUs": "USA",
  "RulesRegionCa": "Kalifornien",
  "RulesActConsent": "Cookie-Einstellungen \x00F6ffnen",
  "RulesActRequest": "Anfrage stellen",
  "RulesActWithdraw": "Ausprobieren",
  "RulesActNotice": "Hinweis \x00F6ffnen",
  "RulesActProduct": "Produkt ansehen",
  "RulesActSellers": "So pr\x00FCfen wir H\x00E4ndler",
  "RulesActImprint": "Impressum \x00F6ffnen",
  "RulesActTerms": "AGB lesen",
  "RulesActChoices": "Auswahl \x00F6ffnen",
  "RulesActNac": "Hinweis lesen",
  "RuleConsentLaw": "DSGVO \x00B7 ePrivacy Art. 5(3)",
  "RuleConsentTitle": "Faire Cookie-Einwilligung",
  "RuleConsentText": "Kein Analyse- oder Marketing-Skript l\x00E4uft vor einem Ja. Ablehnen ist ein Klick, wie Zustimmen.",
  "RuleRightsLaw": "DSGVO Art. 15, 17, 20",
  "RuleRightsTitle": "Auskunft und L\x00F6schung",
  "RuleRightsText": "Kunden sehen, exportieren und l\x00F6schen ihre Daten. Bestelldaten bleiben f\x00FCr die steuerliche Aufbewahrung.",
  "RuleWithdrawLaw": "RL 2011/83/EU Art. 11a",
  "RuleWithdrawDate": "ab 19.06.2026",
  "RuleWithdrawTitle": "Ein Widerrufsbutton",
  "RuleWithdrawText": "Kunden widerrufen einen Kauf online und erhalten eine Best\x00E4tigung per E-Mail.",
  "RuleNoticeLaw": "VO (EU) 2025/1960",
  "RuleNoticeDate": "ab 27.09.2026",
  "RuleNoticeTitle": "Der Hinweis zur Gew\x00E4hrleistung",
  "RuleNoticeText": "Der offizielle EU-Hinweis in der Sprache des Kunden, einen Klick von jedem Produkt entfernt.",
  "RuleGaranLaw": "RL (EU) 2024/825",
  "RuleGaranTitle": "Das GARAN-Haltbarkeitslabel",
  "RuleGaranText": "Garantiert ein Hersteller mehr als 2 Jahre, steht das harmonisierte Label neben dem Preis.",
  "RulePriceLaw": "RL 98/6/EG Art. 6a \x00B7 \x00A7 11 PAngV",
  "RulePriceTitle": "Ehrliche Rabatte",
  "RulePriceText": "Ein reduzierter Preis zeigt den niedrigsten Preis der letzten 30 Tage, aus der eigenen Preishistorie.",
  "RuleSafetyLaw": "GPSR \x00B7 VO (EU) 2023/988",
  "RuleSafetyTitle": "Produktsicherheit",
  "RuleSafetyText": "Jede Produktseite nennt Hersteller, verantwortliche Person in der EU und Produktkennungen.",
  "RuleSellersLaw": "DSA Art. 30 \x00B7 RL 2011/83/EU Art. 6a",
  "RuleSellersTitle": "Gepr\x00FCfte Marktplatz-H\x00E4ndler",
  "RuleSellersText": "H\x00E4ndler geben ihre Unternehmensdaten an, bevor sie verkaufen. Kunden sehen, wer verkauft und ob es ein Unternehmen ist.",
  "RulePackagingLaw": "PPWR \x00B7 VO (EU) 2025/40",
  "RulePackagingDate": "ab 12.08.2026",
  "RulePackagingTitle": "Verpackungsdaten",
  "RulePackagingText": "Material, Gewicht und Rezyklatanteil jeder Verpackung, f\x00FCr die Produktseite und die EPR-Meldungen.",
  "RuleImprintLaw": "\x00A7 5 DDG",
  "RuleImprintTitle": "Das Impressum",
  "RuleImprintText": "Firma, Register und Kontakt kommen aus einem Shop-Profil und f\x00FCllen jeden Rechtstext.",
  "RuleOrderButtonLaw": "\x00A7 312j BGB",
  "RuleOrderButtonTitle": "Der Bestellbutton",
  "RuleOrderButtonText": "Der letzte Button sagt \x201Ezahlungspflichtig bestellen\x201C, wie es das Gesetz verlangt.",
  "RuleTextsLaw": "BGB \x00B7 EGBGB \x00B7 TDDDG",
  "RuleTextsTitle": "Deutsche Rechtstexte",
  "RuleTextsText": "AGB, Datenschutz, Cookies, Widerruf und Retouren als deutsche Vorlagen mit den Daten des Shops.",
  "RuleEprLaw": "VerpackG \x00B7 ElektroG \x00B7 BattDG",
  "RuleEprTitle": "Herstellerregistrierungen",
  "RuleEprText": "Registrierungsnummern f\x00FCr Verpackungen, Elektroger\x00E4te und Batterien, je Land und System.",
  "RuleGpcLaw": "GPC \x00B7 US-Datenschutzgesetze",
  "RuleGpcTitle": "Global Privacy Control",
  "RuleGpcText": "Ein GPC-Signal des Browsers gilt als Widerspruch gegen Verkauf und Weitergabe. Ohne Klick.",
  "RuleOptOutLaw": "US-Datenschutzgesetze",
  "RuleOptOutTitle": "Opt-out-Einwilligung",
  "RuleOptOutText": "US-Besucher erhalten das Opt-out-Modell und schalten jede Kategorie jederzeit ab.",
  "RuleInformLaw": "INFORM Consumers Act",
  "RuleInformTitle": "Gepr\x00FCfte H\x00E4ndler",
  "RuleInformText": "Der Shop speichert die gepr\x00FCften Unternehmensdaten jedes H\x00E4ndlers und zeigt, wer ein Produkt verkauft.",
  "RulePciLaw": "PCI DSS 6.4.3, 11.6.1",
  "RulePciTitle": "Skripte auf der Zahlungsseite",
  "RulePciText": "Checkout-Seiten senden eine Richtlinie mit den erlaubten Skripten. Der Shop protokolliert jedes andere Skript.",
  "RuleChoicesLaw": "CCPA \x00A7 1798.135",
  "RuleChoicesTitle": "Your Privacy Choices",
  "RuleChoicesText": "Das offizielle Opt-out-Symbol und der Link stehen im Fu\x00DF jeder Seite.",
  "RuleNacLaw": "CCPA-Verordnung \x00A7 7012",
  "RuleNacTitle": "Hinweis bei der Erhebung",
  "RuleNacText": "Der Checkout verlinkt den Hinweis dort, wo der Shop personenbezogene Daten erhebt.",
  "RuleRequestsLaw": "CCPA \x00A7 1798.105, 1798.110",
  "RuleRequestsTitle": "Auskunft und L\x00F6schung",
  "RuleRequestsText": "Gepr\x00FCfte Anfragen, mit Fristen, die das Team im Backoffice sieht."
}}>
<#function asH key>
  <#local lang = (locale.getLanguage())!"en">
  <#local v = ((asHomeLabels[lang]!asHomeLabels.en)[key])!((asHomeLabels.en[key])!"")>
  <#if v?has_content><#return v></#if>
  <#return asL(key)>
</#function>
